name: faker_person
description: App to show the details of persons from Faker API

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  connectivity_plus: ^5.0.1
  equatable: ^2.0.5
  fluttertoast: ^8.2.4
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
